services:
  auth-db:
    volumes:
      - type: bind
        source: ./AuthService/src/main/resources/schema.sql
        target: /docker-entrypoint-initdb.d/01-schema.sql
        read_only: true
      - type: bind
        source: ./seed/auth-seed.sql
        target: /docker-entrypoint-initdb.d/02-seed.sql
        read_only: true

  restaurant-db:
    volumes:
      - type: bind
        source: ./RestaurantService/src/main/resources/schema.sql
        target: /docker-entrypoint-initdb.d/01-schema.sql
        read_only: true
      - type: bind
        source: ./seed/restaurant-seed.sql
        target: /docker-entrypoint-initdb.d/02-seed.sql
        read_only: true

  menu-db:
    volumes:
      - type: bind
        source: ./seed/menu-seed.js
        target: /docker-entrypoint-initdb.d/menu-seed.js
        read_only: true

  order-db:
    volumes:
      - type: bind
        source: ./OrderService/src/main/resources/schema.sql
        target: /docker-entrypoint-initdb.d/01-schema.sql
        read_only: true
      - type: bind
        source: ./seed/order-seed.sql
        target: /docker-entrypoint-initdb.d/02-seed.sql
        read_only: true

  rating-db:
    volumes:
      - type: bind
        source: ./RatingService/src/main/resources/schema.sql
        target: /docker-entrypoint-initdb.d/01-schema.sql
        read_only: true
      - type: bind
        source: ./seed/rating-seed.sql
        target: /docker-entrypoint-initdb.d/02-seed.sql
        read_only: true
