from enum import Enum


class EntityType(str, Enum):
    RESTAURANT = "RESTAURANT"
    MENU = "MENU"
    MENU_ITEM = "MENU_ITEM"
    ORDER = "ORDER"


class EventType(str, Enum):
    RESTAURANT_CREATED = "RESTAURANT_CREATED"
    MENU_CREATED = "MENU_CREATED"
    MENU_ITEM_CREATED = "MENU_ITEM_CREATED"
    MENU_ITEM_UPDATED = "MENU_ITEM_UPDATED"
    ORDER_CREATED = "ORDER_CREATED"
    ORDER_STATUS_CHANGED = "ORDER_STATUS_CHANGED"
    ORDER_CANCELLED = "ORDER_CANCELLED"


class OrderStatus(str, Enum):
    CREATED = "CREATED"
    IN_PREPARATION = "IN_PREPARATION"
    READY = "READY"
    DELIVERED = "DELIVERED"
    CANCELLED = "CANCELLED"