
services:
  # Tu parte: El Frontend
  frontend:
    build:
      context: .
      args:
        # Se asume que el backend order-service será mockeado localmente o levantado por fuera mientras
        - VITE_ORDER_SERVICE_URL=http://localhost:8080
        # El tracking service se expone en localhost:8000 para que el NAVEGADOR del cliente pueda accederlo
        - VITE_TRACKING_SERVICE_URL=http://localhost:8000
    ports:
      - "5173:80"
    depends_on:
      - tracking-service
    networks:
      - deliunal-network

  # El servicio real de pedidos (Java)
  order-service:
    build: ./order-service
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - DB_URL=jdbc:postgresql://ep-falling-darkness-add1enig-pooler.c-2.us-east-1.aws.neon.tech/order-service-db?sslmode=require&channelBinding=require
      - DB_USERNAME=neondb_owner
      - DB_PASSWORD=npg_PwcpikZ64rWn
      - JPA_DDL_AUTO=none
      - JPA_SHOW_SQL=false
      - SQL_INIT_MODE=always
      # IMPORTANTE: Reemplazar el url local por el del contenedor tracking-service
      - TRACKING_SERVICE_URL=http://tracking-service:8000
      - LOG_LEVEL=INFO
    networks:
      - deliunal-network

  tracking-service:
    build:
      context: ./tracking-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo-db
    networks:
      - deliunal-network

  mongo-db:
    image: mongo:7
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
      - ./project/1b/mongo-db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - deliunal-network

networks:
  deliunal-network:
    driver: bridge

volumes:
  mongo-data:
