name: Docker Build

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/docker.yml"

jobs:
  docker:
    name: Build imagen Docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build imagen
        working-directory: backend
        run: docker build -t ecommerce-backend:latest .