spring:
  application:
    name: OrderService
  jmx:
    enabled: false

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5436/order_db}
    username: ${SPRING_DATASOURCE_USERNAME:mike}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:mike}
    password: ${SPRING_RABBITMQ_PASSWORD:secret}

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  data:
    jdbc:
      dialect: postgresql

server:
  port: 8085

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health
    jmx:
      exposure:
        exclude: "*"
