apiVersion: v1
kind: Service
metadata:
  name: auth-db
  namespace: clickmunch
  labels:
    app: auth-db
spec:
  type: ClusterIP
  selector:
    app: auth-db
  ports:
    - port: 5432
      targetPort: 5432
