apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-db
  namespace: clickmunch
  labels:
    app: auth-db
spec:
  serviceName: auth-db
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
        - name: postgres
          image: docker.io/bitnami/postgresql:latest
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: clickmunch-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: clickmunch-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickmunch-secrets
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "devuser", "-d", "auth_db"]
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: auth-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: auth-db-storage
          persistentVolumeClaim:
            claimName: auth-db-pvc
