apiVersion: v1
kind: Service
metadata:
  name: apigateway
  namespace: clickmunch
  labels:
    app: apigateway
spec:
  type: NodePort
  selector:
    app: apigateway
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080          # Acceso externo: minikube_ip:30080
