-- =============================================================
-- order-service — Sin datos semilla
-- El Order Service no gestiona catálogo ni usuarios.
-- Las tablas orders y order_items se poblan vía API.
-- =============================================================
