apiVersion: v1
kind: Service
metadata:
  name: notification-db
  namespace: clickmunch
  labels:
    app: notification-db
spec:
  type: ClusterIP
  selector:
    app: notification-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
