apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: activity-service
  template:
    metadata:
      labels:
        app: activity-service
    spec:
      containers:
        - name: activity-service
          image: proyectoplanio-activity_service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
          env:
            - name: PORT
              value: "8001"
            - name: DATABASE_URL
              value: "postgresql://planio_user:planio_pass@postgres:5432/activity_db"
            - name: FIREBASE_PROJECT_ID
              value: "planio-social-todo"
            - name: NOTIFICATION_SERVICE_URL
              value: "http://notification-service:8002"
            - name: ANALYTICS_SERVICE_URL
              value: "http://analytics-service:8004"
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: activity-service
spec:
  type: NodePort
  selector:
    app: activity-service
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30001