apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          imagePullPolicy: Never
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "planio_user"
            - name: POSTGRES_PASSWORD
              value: "planio_pass"
            - name: POSTGRES_DB
              value: "activity_db"
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "planio_user", "-d", "activity_db"]
            initialDelaySeconds: 10
            periodSeconds: 5