export const ROUTES = {
  health: '/health',
  authRegisterCustomer: '/auth/register/customer',
  authRegisterRestaurant: '/auth/register/restaurant',
  authLoginCustomer: '/auth/login/customer',
  authLoginRestaurant: '/auth/login/restaurant',
  authMe: '/auth/me',
  restaurants: '/restaurants',
  restaurantMenu: '/restaurants/:id/menu',
  menuItemAvailability: '/menu-items/:id/availability',
  orders: '/orders',
  orderById: '/orders/:id',
  customerOrders: '/customers/me/orders',
  restaurantOrders: '/restaurants/me/orders',
  kitchenOrders: '/kitchen/orders',
  kitchenOrderStatus: '/kitchen/orders/:id/status',
  orderTimeline: '/orders/:id/timeline',
  promotionsActive: '/promotions/active',
  recommendations: '/recommendations',
} as const;
