events {}

http {
    upstream menu_service {
        server backend-menuservice-1:8084;
        server backend-menuservice-2:8084;
        server backend-menuservice-3:8084;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://menu_service;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
