events {}

http {
    resolver 127.0.0.11 valid=5s ipv6=off;

    limit_req_zone $binary_remote_addr zone=global_limit:10m rate=100r/s;
    limit_req_zone $binary_remote_addr zone=menu_limit:10m rate=10r/s;

    server {
        listen 80;

        location / {
            # Apply the Global Limit (allows brief spikes up to 100)
            limit_req zone=global_limit burst=100 nodelay;

            # Apply the throttling zone to this route
            # burst=10 allows brief spikes of up to 10 requests.
            # nodelay ensures those burst requests are processed immediately, not delayed.
            limit_req zone=menu_limit burst=10 nodelay;

            set $menu_service http://menuservice:8084;
            proxy_pass $menu_service;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
