apiVersion: v1
kind: Service
metadata:
  name: authservice
  namespace: clickmunch
  labels:
    app: authservice
spec:
  type: ClusterIP                    # Solo accesible desde dentro del cluster (vía APIGateway)
  selector:
    app: authservice
  ports:
    - name: http
      port: 8081
      targetPort: 8081
