-- =============================================================
-- order-service — Order DB schema
-- Compatible con PostgreSQL y H2 (modo PostgreSQL)
-- =============================================================

DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;

CREATE TABLE orders (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     BIGINT          NOT NULL,
    restaurant_id   BIGINT          NOT NULL,
    status          VARCHAR(50)     NOT NULL,
    total_amount    NUMERIC(12, 2)  NOT NULL,
    notes           TEXT,
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_orders_customer_id   ON orders(customer_id);
CREATE INDEX idx_orders_restaurant_id ON orders(restaurant_id);
CREATE INDEX idx_orders_status        ON orders(status);

CREATE TABLE order_items (
    id                      BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id                BIGINT          NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    menu_item_id            BIGINT          NOT NULL,
    product_name_snapshot   VARCHAR(255)    NOT NULL,
    unit_price_snapshot     NUMERIC(12, 2)  NOT NULL,
    quantity                INT             NOT NULL CHECK (quantity > 0),
    subtotal                NUMERIC(12, 2)  NOT NULL
);

CREATE INDEX idx_order_items_order_id ON order_items(order_id);
